services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./excel_files_on_host:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
